### ISSUE TITLE
Google Drive Sync not working Brave Browser

### ISSUE THREAD

**Issue by Canaridev** [NabokD/pockettube#98] opened 2024-05-08 15:01 UTC
When I try to sync through Google Drive in Brave Browser I accept all the permises. Althought it bring me to youtube with no syncronization. Help! It's the only way I can sync due to I have my management on Windows Arc and it didn't export with file.

On Windows Arc there is no problem with Google Drive Sync, but it has a problem with exporting the file
When I click on
![Captura de pantalla 2024-05-08 163248](https://github.com/NabokD/pockettube/assets/148588742/b099017d-5785-410f-92e7-1e43b709d685)
Then, I accept all but...
![Captura de pantalla 2024-05-08 163136](https://github.com/NabokD/pockettube/assets/148588742/280fe596-aeaa-4811-a1b3-8482445d0ae7)
Same
![Captura de pantalla 2024-05-08 163329](https://github.com/NabokD/pockettube/assets/148588742/edb91e6d-f624-463b-87d5-8a4da2d4910d)

**Comment by NabokD** [comment] 2024-05-09 22:58
Duplicate of https://www.reddit.com/r/pockettube/comments/1cn3192/google_drive_sync_not_working_brave_browser/

**Closed by NabokD** 2024-05-09 22:58 UTC
