### ISSUE TITLE
#shorts are showing up on Sub Groups regardless of Filter setting

### ISSUE THREAD

**Issue by HidyHo** [NabokD/pockettube#114] opened 2024-08-08 03:54 UTC
I think YT must have changed the logic since Shorts are now cluttering up Subscription Groups even though they are not selected in Filter by Video Type.  

These videos (similar to Geo-locked videos) show up in Sub Groups without DURATION/TIME information so the ways to remove them in the Subscription Groups are:

1) Filter by Duration (anything else but ALL setting)
2) Sort by Video Length (either Ascending or Descending)

I think if you can validate a video with duration information, you can get rid of the issue (FYI, I don't  think Filter by Video Type for Shorts ever worked).

Browser: Chrome Version 126.0.6478.222 (Official Build) (64-bit) 
OS: ChromeOS Version 126.0.6478.222 (Official Build) (64-bit)

**Comment by NabokD** [comment] 2024-08-08 07:41
Filter by Video Type for Shorts is working, could you please send a screenshot with the behavior? Try to disable other extensions, maybe you have a conflict with something.

**Comment by HidyHo** [comment] 2024-08-08 14:08
See below screenshot.  

1) Notice that my filter by type does not include shorts.  
2) The first three videos are SHORTS (found under the Shorts tab for the channel) but appear in the Subscription Group as regular videos.  If I click on these videos, they play like "regular" videos and not as "shorts".  
3) Note that they show up without video duration/time.  If I select or sort videos using TIME, then they will disappear.
4) This issue started just a couple of days ago.  I've disabled all other YT related extensions and the issue still reproducible.

Am I the only one who's having/seeing this issue?

![Screenshot 2024-08-08 8 54 04 PM](https://github.com/user-attachments/assets/1876b1dc-7cae-433e-a6b5-00ff99b28785)

**Comment by NabokD** [comment] 2024-08-08 16:02
It's weird, the same videos are working for me, I don't have idea what it can be and how to reproduce it

![CleanShot 2024-08-08 at 19 00 59@2x](https://github.com/user-attachments/assets/1d0e8570-012a-44ef-8e1b-9029907e9f47)

**Comment by HidyHo** [comment] 2024-08-09 02:10
1) Not sure if it's related but I have my setting on "unwatched" all the time.  Also, not sure what your Filter by Video Type setting is for the above screenshot.

2) Not sure if it's related but around the same time, I noticed that Shorts on the main YT subscription page are acting up.  I have my screen to show 4 videos per line but shorts are showing more (it used to work fine).  Depending on my zoom level, it will show 5 to 7 videos.  I decreased the zoom level for the screenshot below and it shows 6 videos where it used to show 4.  I'm only pointing this out for a possibility that YT might have changed their logic for shorts and how pockettube filter shorts.

![Screenshot 2024-08-09 8 54 17 AM](https://github.com/user-attachments/assets/4f391cf0-0c9b-4958-9438-e7fc0bd6bf47)

**Comment by NabokD** [comment] 2024-08-09 07:14
1. Is not relevant
2. Maybe, we collect shorts from the tab on the channel page, was it updated there too?

**Comment by HidyHo** [comment] 2024-08-09 08:18
Just thinking here ...

If you allow a user to default to "Custom" or any sort of "0 to 60+" filter by duration setting (or change "All" definition to have time/duration validation), it would resolve the issue.  Right now, I can select "custom" in individual groups but if I change a group, it defaults back to "All".  

It would also resolve my previously reported issues where geo-locked videos showing up under subscription groups.  Basically, all problematic videos show up without any time/duration information.

**Comment by NabokD** [comment] 2024-08-10 12:29
I'm not sure it'll be a robust way to do it. Custom can be confusing if you change the group with an applied custom filter you can't see some videos.
We should fix short behavior, but I don't see way how to reproduce it.

**Comment by RomeoAlphaEkko** [comment] 2024-08-18 18:18
have the same problem

- only live and uploads are checked
- the shorts dont go away, if i watch everything, they stay there as "unwatched" while the normal videos disappear
![image](https://github.com/user-attachments/assets/59e394bf-88fe-4b84-bd0c-044f058d52f8)

**Comment by NabokD** [comment] 2024-08-18 21:59
I don't see how to reproduce it, it's working on all of my accounts, maybe YouTube tests some new features on your accounts, but I don't have mass requests about it. I'll add compatibility as soon I get access to YouTube's update if it's really a YouTube test.

**Comment by HidyHo** [comment] 2024-08-20 09:31
Right now, my workaround is the MANUALLY set each subscription group to "Custom" which allows me to see a list of valid videos.  I know setting SHORT, MEDIUM or LONG carries over from one group to another but CUSTOM does not.

If you can allow Custom settings to default then my issue will go away.  It's a reasonable feature to have (allow a user to select a default "from" and "to" duration limit).

**Comment by lasagnaforbrains** [comment] 2024-09-02 09:48
Same behavior here just started for me within the last week. The behavior described is on my YT Premium account. However, on my non-Premium account, pretty much the exact opposite is happening where it does not detect shorts at all. Probably YT testing as mentioned, but figured I'd throw in my experience.

Premium account (all marked as watched, but continue to appear)
![WiVrpgUqDC](https://github.com/user-attachments/assets/52fb3707-2409-4849-b1a1-cf53fee3fed6)

Non-Premium account (I have not marked a single short as watched, yet they still don't appear)
![O8JucOzhPk](https://github.com/user-attachments/assets/628e53f7-7b73-4056-af28-9d947404279c)


Checked in both of these
Brave Version 1.69.160 Chromium: 128.0.6613.114 (Official Build) (64-bit)
Chrome Version 128.0.6613.86 (Official Build) (64-bit)

**Comment by NabokD** [comment] 2024-09-03 14:20
Thank you for sharing!
Yes, on the premium account is weird behavior, I still waiting for the shorts detected to stop working for one of my accounts.

On your non-premium accounts shorts are not showing on Unwatched, it's expected behavior. We showed it around a year ago, but after that came a YouTube update that disabled a way to detect whether shorts were watched or not, so we just hide it when the unwatched filter is enabled.

**Comment by NabokD** [comment] 2024-09-04 07:23
The new version 16.2.13 is available on Chrome with fixing it. It was a YouTube update that came to me too, try to use it!

**Closed** 2024-09-06 06:52 UTC

**Comment by lasagnaforbrains** [comment] 2025-02-25 12:18
This issue seems to be happening for me again. It also doesn't seem to be considering my watched status as "All Videos" and "Unwatched" are showing me the same results despite me having have already watched everything in the list.

**Comment by NabokD** [comment] 2025-02-25 12:44
I can't reproduce it under my account, let's wait for, maybe it's another YouTube update will come
